### ISSUE TITLE
Using lkprf with offline PRF data

### ISSUE THREAD

**Issue by astrobel** [lightkurve/lkprf#11]
Hi! I'm working with a largely offline codebase that runs on TESS data downloaded in bulk, which includes the PRF files. I was wondering if there's a way to get lkprf to interface with the local files rather than downloading new ones, or if there are plans for such a feature in the future? Thanks!

**Comment by Nschanche** [comment]
Hi @astrobel, lkprf caches the files locally, so it should only download the files the first time you access a new camera/ccd. The files are by default stored in lkprf/data. 
In the case of TESS, the files are modified before being saved to disk to 'cutout' the pixels that contribute to the PRF and zero out the remaining pixels to match the structure of the Kepler files, so they are not an exact match to the files found on the MAST archive.

**Comment by astrobel** [comment]
@Nschanche This is very good to know! Thanks so much for your response to this and also to issue #12, the download path option would resolve this issue on my end.

**Comment by Nschanche** [comment]
Closing as v1.1.1 now allows users to specify a directory to read/write files, (also see issue #12).
