### ISSUE TITLE
Specifying download path

### ISSUE THREAD

**Issue by astrobel** [lightkurve/lkprf#12]
Hi again! Related question to issue #11 that I just posted, but I think different enough in specifics to warrant its own issue. I am running lkprf on a supercomputer, which does not allow any data storage at `/usr/local/software`, so the download functionality will not work. Would it be possible to implement an optional user-specified download path to avoid this issue?

**Comment by Nschanche** [comment]
Hi @astrobel, yes I think that sounds like a good idea. I'll take a look at adding that feature.

**Comment by Nschanche** [comment]
Hi @astrobel , we've released a new version of lkprf that adds a cache_dir parameter. You can now specify the path for where you would like to store the files. If left unspecified it remains in lkprf/data/. Please let me know if you find any issues with this.

**Comment by astrobel** [comment]
@Nschanche Thanks so much for this, I really appreciate it! It's working perfectly.
