### ISSUE TITLE
different TESS PRF models for Sectors 1-3

### ISSUE THREAD

**Issue by keatonb** [lightkurve/lkprf#5]
The TESS mission provides different PRF models for Sectors 1-3 than later sectors https://heasarc.gsfc.nasa.gov/docs/tess/observing-technical.html#point-spread-function

Can sector number be specified to access these different data products, perhaps defaulting to the later PRF models if sector isn't specified?

**Comment by Nschanche** [comment]
You are correct @keatonb, there were PRF models produced for sectors 1-3.  I agree that some users may be interested in accessing these files. 

I've created PR #9 that adds in the ability to specify a sector. If sector 1-3 is selected, the early PRF models will be downloaded. If a higher sector (or no sector) is specified, the later models will be selected.

**Comment by Nschanche** [comment]
Changed merged with PR #9.
